bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    implementation project(':shop-common')
    implementation project(':shop-domain')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter'
    
    // Spring Web (Filter, HttpServletRequest 등을 위해 필요)
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.springframework.security:spring-security-core'
    implementation 'org.springframework.security:spring-security-crypto'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
}
