bootJar {
    enabled = true
}

jar {
    enabled = false
}

dependencies {
    implementation project(':shop-common')
    implementation project(':shop-domain')
    implementation project(':shop-core')
    
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    
    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'com.h2database:h2'
}
